export const listOfCharges = [
  {
    name: 'Czynsz',
    paid0: false,
    paid1: false,
    paid2: false,
    paid3: false,
    paid4: false,
    paid5: false,
    paid6: false,
    paid7: false,
    paid8: false,
    paid9: false,
    paid10: false,
    paid11: false,
  },
  {
    name: 'Prąd',
    paid0: false,
    paid1: false,
    paid2: false,
    paid3: false,
    paid4: false,
    paid5: false,
    paid6: false,
    paid7: false,
    paid8: false,
    paid9: false,
    paid10: false,
    paid11: false,
  },
  {
    name: 'Gaz',
    paid0: false,
    paid1: false,
    paid2: false,
    paid3: false,
    paid4: false,
    paid5: false,
    paid6: false,
    paid7: false,
    paid8: false,
    paid9: false,
    paid10: false,
    paid11: false,
  },
  {
    name: 'Rata za samochód',
    paid0: false,
    paid1: false,
    paid2: false,
    paid3: false,
    paid4: false,
    paid5: false,
    paid6: false,
    paid7: false,
    paid8: false,
    paid9: false,
    paid10: false,
    paid11: false,
  },
];

export const months = [
  'Styczeń',
  'Luty',
  'Marzec',
  'Kwiecień',
  'Maj',
  'Czerwiec',
  'Lipiec',
  'Sierpień',
  'Wrzesień',
  'Październik',
  'Listopad',
  'Grudzień',
];
